name: Build and Test C Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt update && sudo apt install -y build-essential

    - name: Build library and tests
      run: make all

    - name: Run tests
      run: make test
